"""initial_schema

Revision ID: 3b610152cf34
Revises: 
Create Date: 2026-09-17 12:21:58.117348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b610152cf34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_request_id'), 'agent_runs', ['request_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('reviewers',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_external_id'), 'reviewers', ['external_id'], unique=True)
    op.create_index(op.f('ix_reviewers_id'), 'reviewers', ['id'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('trust_rating', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('agent_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_agent_name'), 'agent_steps', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_steps_id'), 'agent_steps', ['id'], unique=False)
    op.create_index(op.f('ix_agent_steps_run_id'), 'agent_steps', ['run_id'], unique=False)
    op.create_index('ix_agent_steps_run_order', 'agent_steps', ['run_id', 'step_order'], unique=False)
    op.create_table('compatibility_rules',
    sa.Column('category_a_id', sa.UUID(), nullable=True),
    sa.Column('category_b_id', sa.UUID(), nullable=True),
    sa.Column('rule_type', sa.String(length=60), nullable=False),
    sa.Column('parameter_key', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_a_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_b_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_rules_category_a_id'), 'compatibility_rules', ['category_a_id'], unique=False)
    op.create_index(op.f('ix_compatibility_rules_category_b_id'), 'compatibility_rules', ['category_b_id'], unique=False)
    op.create_index(op.f('ix_compatibility_rules_id'), 'compatibility_rules', ['id'], unique=False)
    op.create_index(op.f('ix_compatibility_rules_rule_type'), 'compatibility_rules', ['rule_type'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_storage_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_jobs_url'), 'crawl_jobs', ['url'], unique=False)
    op.create_table('products',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_component', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_category_is_component', 'products', ['category_id', 'is_component'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_component'), 'products', ['is_component'], unique=False)
    op.create_index(op.f('ix_products_model_number'), 'products', ['model_number'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    op.create_table('components',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=False),
    sa.Column('package_type', sa.String(length=80), nullable=True),
    sa.Column('pin_count', sa.Integer(), nullable=True),
    sa.Column('mounting_type', sa.String(length=50), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=40), nullable=False),
    sa.Column('datasheet_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_package_type'), 'components', ['package_type'], unique=False)
    op.create_index(op.f('ix_components_part_number'), 'components', ['part_number'], unique=True)
    op.create_index(op.f('ix_components_product_id'), 'components', ['product_id'], unique=True)
    op.create_table('documents',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_product_id'), 'documents', ['product_id'], unique=False)
    op.create_table('images',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('visual_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_image_type'), 'images', ['image_type'], unique=False)
    op.create_index(op.f('ix_images_product_id'), 'images', ['product_id'], unique=False)
    op.create_table('model_calls',
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_id'), 'model_calls', ['id'], unique=False)
    op.create_index(op.f('ix_model_calls_model_name'), 'model_calls', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_calls_step_id'), 'model_calls', ['step_id'], unique=False)
    op.create_table('product_relationships',
    sa.Column('product_a_id', sa.UUID(), nullable=False),
    sa.Column('product_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_a_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_b_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prod_rel_unique', 'product_relationships', ['product_a_id', 'product_b_id', 'relationship_type'], unique=True)
    op.create_index(op.f('ix_product_relationships_id'), 'product_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_product_relationships_product_a_id'), 'product_relationships', ['product_a_id'], unique=False)
    op.create_index(op.f('ix_product_relationships_product_b_id'), 'product_relationships', ['product_b_id'], unique=False)
    op.create_index(op.f('ix_product_relationships_relationship_type'), 'product_relationships', ['relationship_type'], unique=False)
    op.create_table('product_sources',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_sku', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('crawl_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sources_external_sku'), 'product_sources', ['external_sku'], unique=False)
    op.create_index(op.f('ix_product_sources_id'), 'product_sources', ['id'], unique=False)
    op.create_index('ix_product_sources_prod_source', 'product_sources', ['product_id', 'source_id'], unique=True)
    op.create_index(op.f('ix_product_sources_product_id'), 'product_sources', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_sources_source_id'), 'product_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_product_sources_source_url'), 'product_sources', ['source_url'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_sku'), 'product_variants', ['sku'], unique=True)
    op.create_table('reviews',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=True),
    sa.Column('use_case', sa.String(length=100), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Float(), nullable=False),
    sa.Column('attributes_analyzed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_fraud_score', 'reviews', ['fraud_score'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_product_id'), 'reviews', ['product_id'], unique=False)
    op.create_index('ix_reviews_product_rating', 'reviews', ['product_id', 'rating'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_reviewed_at'), 'reviews', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_sentiment'), 'reviews', ['sentiment'], unique=False)
    op.create_index(op.f('ix_reviews_source_id'), 'reviews', ['source_id'], unique=False)
    op.create_index(op.f('ix_reviews_use_case'), 'reviews', ['use_case'], unique=False)
    op.create_table('availabilities',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilities_id'), 'availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_availabilities_product_id'), 'availabilities', ['product_id'], unique=False)
    op.create_index(op.f('ix_availabilities_source_id'), 'availabilities', ['source_id'], unique=False)
    op.create_index(op.f('ix_availabilities_status'), 'availabilities', ['status'], unique=False)
    op.create_index(op.f('ix_availabilities_variant_id'), 'availabilities', ['variant_id'], unique=False)
    op.create_table('component_specifications',
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('voltage_min', sa.Float(), nullable=True),
    sa.Column('voltage_max', sa.Float(), nullable=True),
    sa.Column('voltage_unit', sa.String(length=10), nullable=False),
    sa.Column('current_min', sa.Float(), nullable=True),
    sa.Column('current_max', sa.Float(), nullable=True),
    sa.Column('current_unit', sa.String(length=10), nullable=False),
    sa.Column('resistance', sa.Float(), nullable=True),
    sa.Column('resistance_unit', sa.String(length=10), nullable=True),
    sa.Column('capacitance', sa.Float(), nullable=True),
    sa.Column('capacitance_unit', sa.String(length=10), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.Column('power_unit', sa.String(length=10), nullable=True),
    sa.Column('tolerance', sa.String(length=20), nullable=True),
    sa.Column('interface', sa.String(length=80), nullable=True),
    sa.Column('package', sa.String(length=80), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('frequency_unit', sa.String(length=10), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('extra_specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comp_spec_temp', 'component_specifications', ['temperature_min', 'temperature_max'], unique=False)
    op.create_index('ix_comp_spec_voltage', 'component_specifications', ['voltage_min', 'voltage_max'], unique=False)
    op.create_index(op.f('ix_component_specifications_component_id'), 'component_specifications', ['component_id'], unique=True)
    op.create_index(op.f('ix_component_specifications_id'), 'component_specifications', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_amount'), 'prices', ['amount'], unique=False)
    op.create_index('ix_prices_amount_currency', 'prices', ['amount', 'currency'], unique=False)
    op.create_index(op.f('ix_prices_currency'), 'prices', ['currency'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index('ix_prices_prod_rec', 'prices', ['product_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_recorded_at'), 'prices', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_prices_source_id'), 'prices', ['source_id'], unique=False)
    op.create_index(op.f('ix_prices_variant_id'), 'prices', ['variant_id'], unique=False)
    op.create_table('specifications',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('spec_group', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specifications_id'), 'specifications', ['id'], unique=False)
    op.create_index(op.f('ix_specifications_key'), 'specifications', ['key'], unique=False)
    op.create_index('ix_specifications_product_group_key', 'specifications', ['product_id', 'spec_group', 'key'], unique=False)
    op.create_index(op.f('ix_specifications_product_id'), 'specifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_specifications_spec_group'), 'specifications', ['spec_group'], unique=False)
    op.create_index(op.f('ix_specifications_variant_id'), 'specifications', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specifications_variant_id'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_spec_group'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_product_id'), table_name='specifications')
    op.drop_index('ix_specifications_product_group_key', table_name='specifications')
    op.drop_index(op.f('ix_specifications_key'), table_name='specifications')
    op.drop_index(op.f('ix_specifications_id'), table_name='specifications')
    op.drop_table('specifications')
    op.drop_index(op.f('ix_prices_variant_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_source_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_recorded_at'), table_name='prices')
    op.drop_index(op.f('ix_prices_product_id'), table_name='prices')
    op.drop_index('ix_prices_prod_rec', table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_currency'), table_name='prices')
    op.drop_index('ix_prices_amount_currency', table_name='prices')
    op.drop_index(op.f('ix_prices_amount'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_component_specifications_id'), table_name='component_specifications')
    op.drop_index(op.f('ix_component_specifications_component_id'), table_name='component_specifications')
    op.drop_index('ix_comp_spec_voltage', table_name='component_specifications')
    op.drop_index('ix_comp_spec_temp', table_name='component_specifications')
    op.drop_table('component_specifications')
    op.drop_index(op.f('ix_availabilities_variant_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_status'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_source_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_product_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_id'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_index(op.f('ix_reviews_use_case'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_source_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_sentiment'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewed_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index('ix_reviews_product_rating', table_name='reviews')
    op.drop_index(op.f('ix_reviews_product_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index('ix_reviews_fraud_score', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_product_variants_sku'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_product_sources_source_url'), table_name='product_sources')
    op.drop_index(op.f('ix_product_sources_source_id'), table_name='product_sources')
    op.drop_index(op.f('ix_product_sources_product_id'), table_name='product_sources')
    op.drop_index('ix_product_sources_prod_source', table_name='product_sources')
    op.drop_index(op.f('ix_product_sources_id'), table_name='product_sources')
    op.drop_index(op.f('ix_product_sources_external_sku'), table_name='product_sources')
    op.drop_table('product_sources')
    op.drop_index(op.f('ix_product_relationships_relationship_type'), table_name='product_relationships')
    op.drop_index(op.f('ix_product_relationships_product_b_id'), table_name='product_relationships')
    op.drop_index(op.f('ix_product_relationships_product_a_id'), table_name='product_relationships')
    op.drop_index(op.f('ix_product_relationships_id'), table_name='product_relationships')
    op.drop_index('ix_prod_rel_unique', table_name='product_relationships')
    op.drop_table('product_relationships')
    op.drop_index(op.f('ix_model_calls_step_id'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_model_name'), table_name='model_calls')
    op.drop_index(op.f('ix_model_calls_id'), table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_images_product_id'), table_name='images')
    op.drop_index(op.f('ix_images_image_type'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_documents_product_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_components_product_id'), table_name='components')
    op.drop_index(op.f('ix_components_part_number'), table_name='components')
    op.drop_index(op.f('ix_components_package_type'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_model_number'), table_name='products')
    op.drop_index(op.f('ix_products_is_component'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('ix_products_category_is_component', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_crawl_jobs_url'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_source_id'), table_name='crawl_jobs')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_compatibility_rules_rule_type'), table_name='compatibility_rules')
    op.drop_index(op.f('ix_compatibility_rules_id'), table_name='compatibility_rules')
    op.drop_index(op.f('ix_compatibility_rules_category_b_id'), table_name='compatibility_rules')
    op.drop_index(op.f('ix_compatibility_rules_category_a_id'), table_name='compatibility_rules')
    op.drop_table('compatibility_rules')
    op.drop_index('ix_agent_steps_run_order', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_run_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_agent_name'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_reviewers_id'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_external_id'), table_name='reviewers')
    op.drop_table('reviewers')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_request_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
